Polycube CI with GitHub Actions
polycube-network/polycube pull request #364
Opened 2021-03-02 15:23 UTC by klaalk

2021-03-17 16:28 UTC, frisso commented on .github/workflows/ci.yml
> +  # This job deal with building the application
```suggestion
  # This job deals with building the application
```

2021-03-17 16:29 UTC, frisso commented on .github/workflows/ci.yml
> +  # This job deal with tests
```suggestion
  # This job deals with tests
```

2021-03-17 16:30 UTC, frisso approved these changes

2021-03-30 07:53 UTC, FedeParola requested changes

2021-03-30 07:53 UTC, FedeParola commented on Documentation/developers/polycube-ci.rst
> +This workflow is used to validate any open PR for this reason all tests are performed after the build. If there is only one failed test, the entire workflow will end in error, reporting it via annota
```suggestion
This workflow is used to validate any open PR for this reason all tests are performed after the build. If there is only one failed test, the entire workflow will end in error, reporting it via annotation. Furthermore, it is possible to find the logs of the tests through the artifact section within the page of the performed workflow.
```

2021-03-30 07:53 UTC, FedeParola commented on Documentation/developers/polycube-ci.rst
> +In this state only polycube in default will be built and published on docker under the "polycubenets" repository with it development names "polycube-pr".
```suggestion
In this state only the full polycube image will be built and published on **Docker Hub** under the ``polycubenets/polycube-pr`` repository.
```

2021-03-30 07:53 UTC, FedeParola commented on Documentation/developers/polycube-ci.rst
> +Once validated and accepted a PR this workflow start in order to updated the latest version of polycube by publishing the new image on "polycubenets" repository.
```suggestion
Once validated and accepted a PR this workflow start in order to updated the latest version of polycube by publishing the new image on ``polycubenets`` repository.
```

2021-03-30 07:53 UTC, FedeParola commented on Documentation/developers/polycube-ci.rst
> +Here the individual names change to polycube, polycube-iptables and polycube-k8s.
Three different images are published: ``polycube``, the full polycube image; ``polycube-iptables``, containing only the files needed to run the polycube clone of iptables; and ``polycube-k8s``, containing only the CNI plugin for Kubernetes.

2021-03-30 07:53 UTC, FedeParola commented on Documentation/developers/polycube-ci.rst
> +This workflow is used to release an official polycube tag. The new image will always be built and published on the "polycubenets" repository with the official names (polycube, polycube-iptables and p
```suggestion
This workflow is used to release an official polycube tag. The new image will always be built and published on the ``polycubenets`` repository with the official names (polycube, polycube-iptables and polycube-k8s).
```

2021-03-30 12:52 UTC, FedeParola approved these changes

2021-03-31 06:03 UTC, frisso commented on Documentation/developers/polycube-ci.rst
> +Once validated and accepted a PR this workflow start in order to updated the latest version of polycube by publishing the new image on ``polycubenets`` repository.
```suggestion
This workflow starts once a PR is validated and accepted and it updates the _latest_ version of polycube by publishing the new image on ``polycubenets`` repository.
```

2021-03-31 06:07 UTC, frisso commented on Documentation/developers/codegen.rst
>  In order to run the image, it is needed to mount a volume into ``/polycube-base-datamodels`` where the base datamodels are located on the host (by default ``/usr/local/include/polycube/datamodel-comm
```suggestion
In order to run the image, you need to mount a volume into ``/polycube-base-datamodels`` where the base datamodels are located on the host (by default ``/usr/local/include/polycube/datamodel-common/``).
Furthermore, you need also to mount a volume to share the input yang model and the output folder.
```

2021-03-31 06:08 UTC, frisso commented on Documentation/developers/polycube-ci.rst
> +This workflow is used to validate any open PR for this reason all tests are performed after the build. If there is only one failed test, the entire workflow will end in error, reporting it via annota
```suggestion
This workflow is used to validate any open PR. For this reason, all tests are performed after the build. If there is only one failed test, the entire workflow will end in error, reporting it via annotation. Furthermore, it is possible to find the logs of the tests through the artifact section within the page of the performed workflow.
```

2021-03-31 06:11 UTC, frisso commented on Documentation/developers/polycube-ci.rst
> +  1.  PR opened/synchronized/reopened
```suggestion
  1.  **Pull Request (PR) opened/synchronized/reopened**: used to build and test any open PRs. The workflow assumes a "dev" state for its entire duration.
```

2021-03-31 06:12 UTC, frisso commented on Documentation/developers/polycube-ci.rst
> +  2.  Commit push on master (PR accepted)
```suggestion
  2.  **Commit push on master (PR accepted)**: used to build and push an updated version of polycube on the public docker registry after a PR merge. In this situation the status of the workflow assumes the value of "master".
```

2021-03-31 06:12 UTC, frisso commented on Documentation/developers/polycube-ci.rst
> +  3.  Tag push on master (tag with format "v*")
```suggestion
  3.  **Tag push on master (tag with format "v*")**: used to build and push a polycube release on the public docker registry with an official tag. The status of the workflow becomes "release" and a changelog is also published on github starting from the last release.
```

2021-03-31 06:12 UTC, frisso commented on Documentation/developers/polycube-ci.rst
> +The first event is used to build and test any open PRs, then the workflow assumes a "dev" state for its entire duration.
```suggestion
```

2021-03-31 06:13 UTC, frisso commented on Documentation/developers/polycube-ci.rst
> +The second workflow is used to build and push an updated version of polycube on docker after a PR merge. In this situation the status of the workflow assumes the value of "master".
```suggestion
```

2021-03-31 06:13 UTC, frisso commented on Documentation/developers/polycube-ci.rst
> +The third event is used to build and push a polycube release on docker with an official tag. The status of the workflow becomes "release" and a changelog is also published on github starting from the
```suggestion
```

2021-04-02 10:21 UTC, FedeParola commented
Can the merge be forced? Jenkins tests won't pass (since the system doesn't exist anymore). I don't have the privilege to merge

2021-04-06 06:14 UTC, merged