A possible solution to solve bug #350
polycube-network/polycube pull request #385
Opened 2021-07-02 18:23 UTC by pinoOgni

This PR fixes bug #350  

The error was that before deleting the secondaryip, (by calling the `delete_router_ports_secondaryip_by_id` method which calls `delSecondaryip`), the method `read_router_ports_secondaryip_by_id` was called which inside calls `getSecondaryip(ip)`. Here  the case in which a secondaryip was not present was not handled (both because does not exist or because the port has no secondaryip or even the main ip address).

In the proposed solution, the `getSecondaryip` method returns nullptr if it does not find the secondaryip and then in the `read_router_ports_secondaryip_by_id method` an empty `PortsSecondaryipJsonObject` is returned; doing so will call the `delete_router_ports_secondaryip_by_id` (like a normal execution) method which will handle the error displaying it to the user.

Here there is an example:
```
netgroup@giuseppe:~$ polycubectl router r1
netgroup@giuseppe:~$ polycubectl r1 ports p1
netgroup@giuseppe:~$ polycubectl r1 ports p1 secondaryip del 1.1.1.3/24
Address does not exist (or it is not a secondary address)

netgroup@giuseppe:~$ polycubectl r1 ports p1 set ip=1.1.1.1/24
netgroup@giuseppe:~$ polycubectl r1 ports p1 secondaryip del 1.1.1.3/24
Address does not exist (or it is not a secondary address)

netgroup@giuseppe:~$ polycubectl r1 ports p1 secondaryip add 1.1.1.100/24
netgroup@giuseppe:~$ polycubectl r1 ports p1 secondaryip add 1.1.1.99/24
netgroup@giuseppe:~$ polycubectl r1 ports p1 secondaryip del  1.1.1.99/24
netgroup@giuseppe:~$polycubectl r1 ports p1 secondaryip del  1.1.1.99/24
Address does not exist (or it is not a secondary address)
```

2021-07-03 13:27 UTC, FedeParola requested changes
Hi @pinoOgni,
unless strictly necessary I would avoid editing the `RouterApiImpl.cpp` that is auto-generated and should not be modified. It should be enough to just throw an exception in the `Ports::getSecondaryip()` method if the secondary ip is not found. Can you test it?

2021-07-03 23:36 UTC, pinoOgni commented
> Hi @pinoOgni,
> unless strictly necessary I would avoid editing the `RouterApiImpl.cpp` that is auto-generated and should not be modified. It should be enough to just throw an exception in the `Ports::getSecondaryip()` method if the secondary ip is not found. Can you test it?

Hi @FedeParola, you are right, I did not remember the constraint of not modifying the `RouterApiImpl.cpp` file. In any case I had tried to throw an exception in the `Ports::getSecondaryip` method but in doing so, the error message is not displayed to the user (as happens for example in the case of the `Ports::addSecondaryip`), but, there is only one error of this type (the throw error is not really seen):

```
netgroup@giuseppe:~$ polycubectl router r1
netgroup@giuseppe:~$ polycubectl r1 ports p1
netgroup@giuseppe:~$ polycubectl r1 ports p1 secondaryip del  1.1.1.99/24
{"ietf-restconf:errors":{"error":[{"error-type":"application","error-tag":"data-missing"}]}}
````

This solves the segmentation error since the `toJsonObject()` method is not called but I don't know if that's enough. What do you think about it? Do I push this last change or try to figure out how to make the user see an error? 
Although sadly, the only way I had found was to edit the `RouterApiImpl` file.

2021-07-04 13:12 UTC, FedeParola commented
I see, the behavior is strange...
When removing a port that does not exist for example we obtain the same json error:
`{"ietf-restconf:errors":{"error":[{"error-type":"application","error-tag":"data-missing"}]}}`
However when deleting a route that does not exist, we get the plain exception message:
`Cannot find a matching route.`
We should investigate why there are two different responses and possibly select just one.
For now however I would just fix the bug as we said, since it is compatible with the current behavior of Polycube.

2021-07-04 18:29 UTC, pinoOgni commented
> I see, the behavior is strange...
> When removing a port that does not exist for example we obtain the same json error:
> `{"ietf-restconf:errors":{"error":[{"error-type":"application","error-tag":"data-missing"}]}}`
> However when deleting a route that does not exist, we get the plain exception message:
> `Cannot find a matching route.`
> We should investigate why there are two different responses and possibly select just one.
> For now however I would just fix the bug as we said, since it is compatible with the current behavior of Polycube.

OK, I agree. I update the changes.

2021-07-05 05:54 UTC, frisso commented
/rebase

2021-07-05 07:55 UTC, FedeParola approved these changes

2021-07-05 08:15 UTC, merged